### ISSUE TITLE
module command not the same as in CLI

### ISSUE THREAD

**Issue by alikhani** [graphcool/modules#15]
This returns that module isn't a graphcool command but modules:
`graphcool module add graphcool/modules/authentication/facebook` (doesn't work)
`graphcool modules add graphcool/modules/authentication/facebook` (this works)

So this need a change in the readme or the cli

**Comment by alikhani** [comment]
@marktani great! 
Another thing missing in the README that you could add is that before trying the authentication in graphcool playground they have to do a `graphcool deploy`.. At least I had to (I'm kind of new to graphcool so maybe did something wrong)

**Comment by marktani** [comment]
Thanks @alikhani, I hope this is clearer: https://github.com/graphcool/modules/commit/ae3f99098052c14b18b3681a82631509d494d2a4

**Comment by marktani** [comment]
awesome, thanks a lot for your feedback! 🙂 please have a look at this thread for more information about the new CLI: https://www.graph.cool/forum/t/feedback-new-cli-beta/949?u=nilan.
