### ISSUE TITLE
Facebook code file naming incorrect

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/modules#18]
The graphcool.yml references different file names than the src folder contains.

**Comment by lrettig** [comment]
I get an error when I try to `graphcool modules add graphcool/modules/authentication/facebook`. I wonder if it's related:

```
   Downloading module graphcool/modules/authentication/facebook from graphcool/modules ... ✔
 ▸    Cannot read property 'modules' of undefined

Get in touch if you need help: https://www.graph.cool/forum
```

**Comment by kbrandwijk** [comment]
@lrettig Did you already initialize a project in the folder where you execute this command? I got that error before, but then I didn't have a graphcool.yml file in my folder.

**Comment by lrettig** [comment]
@kbrandwijk I had run init with an earlier version of the CLI tool. Running again with `graphcool@beta` is producing another error:

```
> rm -rf modules/
> graphcool modules add graphcool/modules/authentication/facebook
   Downloading module graphcool/modules/authentication/facebook from graphcool/modules ... ✔
 ▸    Cannot read property 'endPosition' of undefined
```

**Comment by stephenhandley** [comment]
@marktani yep looks like the issue is that the yml file specifies
https://github.com/graphcool/modules/blob/master/authentication/facebook/graphcool.yml#L7-L9 things in camelCase and the file names are dash separated i.e. `facebookAuthentication.js` vs. `facebook-authentication.js`

**Comment by kbrandwijk** [comment]
@stephenhandley I already created a PR: #19

**Comment by stephenhandley** [comment]
@kbrandwijk ah shit, my bad i missed that above, sorry for the noise!
