### ISSUE TITLE
Is it possible to return several fields in the payload?

### ISSUE THREAD

**Issue by mkozhukharenko** [graphcool/modules#22]
I want to return additional field 'authType' which ca be either 'login' or 'signUp' string

```
type AuthenticateFacebookUserPayload {
  token: String!
  authType: String!
}
```

is it possible to implement?  I tried but failed (

**Comment by marktani** [comment]
Sure, that's possible. You just need to make sure to also return an object of this shape:

```
{
  data: {
    token: "",
    authType: "",
  }
}
``

**Comment by mkozhukharenko** [comment]
I've tried that. 

I returned this object from my function

```
{
  data: {
    token: "",
    authType: "",
  }
}
```
and I see that such object is coming to graphcool in logs output

```
{"event":"{ "data": ,"returnValue":{"data":{"token":"","authType":"login"}}}
```

but client receives only 'token' (I'm using apollo-client for fetching)

**Comment by marktani** [comment]
Did you include the field in the query?

**Comment by mkozhukharenko** [comment]
I did

```
type AuthenticateAccountKitUserPayload {
    token: String!
    authType: String!
}

extend type Mutation {
    authenticateAccountKitUser(accountKitToken: String!): AuthenticateAccountKitUserPayload
}

```

**Comment by marktani** [comment]
I mean in the query in your client 🙂

**Comment by mkozhukharenko** [comment]
my fault, I forget to do that. Sorry for taking your time.

**Comment by marktani** [comment]
no problem at all!
