### ISSUE TITLE
File API - upload not working

### ISSUE THREAD

**Issue by maticzav** [graphcool/modules#23]
Hi!

I am trying to use Graphcool File API, but every time I create a request to the server if fails.

The error returned by fetch is something like this:
`graphcool.js?9cab083:10 POST __API_URL__::ERR_CONNECTION_RESET`

Any idea why this might be happening?

```js
import fetch from 'isomorphic-fetch'

export const uploadFile = file => {
   const data = new FormData()
   data.append('data', file)

   return fetch(GRAPHCOOL_FILE_URL, {
      method: 'POST',
      headers: {
         origin: 'same-origin',
         'Content-Type': 'multipart/form-data'
      },
      body: data
   }).then(res => res.json())
}
```

**Comment by kbrandwijk** [comment]
Can you double-check the `GRAPHCOOL_FILE_URL` with the endpoints displayed in the console?

**Comment by maticzav** [comment]
I have checked! It's the one written next to `File API:`. It still doesn't work though, I mean it's the same `url`.

**Comment by maticzav** [comment]
I have figured out the problem:

My old schema included `@model` in its definition:
```
type File (@model) <- this {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}
```

and that's why it didn't work.

Thank you!
