### ISSUE TITLE
Sooo... grapchool module command does not exist?

### ISSUE THREAD

**Issue by GxDesign** [graphcool/modules#24]
I just updated graphcool and im getting an error that the module command does not exist for:
graphcool modules add graphcool/modules/authentication/email-password

cant install. any insight?

**Comment by GxDesign** [comment]
Ahh, I see theyre templates now. The link I used for this wasnt updated, would be good to update the read.me here.

**Comment by GxDesign** [comment]
moved to templates, got it. used an old link for the email-password module.

**Comment by marktani** [comment]
Hey Giancarlo, where did you follow the link? So I can update it to point to the templates instead 🙂
