### ISSUE TITLE
Add env vars to algolia module

### ISSUE THREAD

**Issue by marktani** [graphcool/modules#6]
also update README

**Comment by lifeiscontent** [comment]
I'm wondering if I should follow these instructions?

![screen shot 2017-09-23 at 2 24 07 am](https://user-images.githubusercontent.com/180963/30760901-65bbfb44-a006-11e7-9100-6241087f1f2e.png)

**Comment by marktani** [comment]
you can do that if you need to use different Algolia environments, but you don't have to.

Just make sure to use the same index name in Algolia as in the module 🙂

**Comment by lifeiscontent** [comment]
@marktani but in the case of graphcool, there aren't any envs right its just "prod"

**Comment by lifeiscontent** [comment]
or is there a recommendation about having many envs in graphcool?

**Comment by marktani** [comment]
the `.graphcoolrc` file lets you control different environments - most command shave an `--env` or `-e` parameter. furthermore, we're working on a generic migrations concepts that lets you apply changes from one project to another: https://github.com/graphcool/cli/issues/173
